name: Docker Image CI

on:
  push:
    tags: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : JSON to variables
        uses: antifree/json-to-variables@v1.1.1
        with:
          filename: 'release.json'
    
      - name: show output
        run : echo "${{ env.analyzer }}"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jeffersonlab/halla-sbs-offline
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: 'linux/amd64,linux/arm64'
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            DOCKER_TAG=${{ steps.meta.outputs.tags }}
            APP_VERSION=${{ github.ref_name}}
            REPO_NAME=${{ github.event.repository.name }}
            ANALYZER_VERSION=${{ env.analyzer }}
